# Generated by Django 5.2 on 2025-04-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
