# Generated by Django 5.2 on 2025-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
