# Generated by Django 5.2 on 2025-04-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_remove_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
