# Generated by Django 5.2 on 2025-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_books_profile_student_delete_user_profile_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
