# Generated by Django 5.2 on 2025-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_student_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=0, upload_to='Gallery'),
        ),
    ]
