# Generated by Django 5.2 on 2025-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0013_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='spy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=90),
        ),
    ]
